In [1]:
import numpy as np
import pandas as pd

## Dataframes, Series and Panel Objects

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
#data = [[1,2,3],[4,5,6]]
data={'A':[1,2,3],'B':[4,5,6]}
df = pd.DataFrame(data)
df

A  B
0  1  4
1  2  5
2  3  6

In [6]:
arr2[0,:]

array([1, 2, 3])

In [7]:
df['A']

0    1
1    2
2    3
Name: A, dtype: int64

In [10]:
data = {'Item1' : pd.DataFrame(np.random.randn(4, 3)), 
        'Item2' : pd.DataFrame(np.random.randn(4, 2))}
p = pd.Panel(data)

In [11]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2

## Importing and Exporting data

In [12]:
df = pd.read_json('df.json')

In [13]:
df

birthyear  children    hobby  weight
alice         1985       NaN   Biking      68
bob           1984       3.0  Dancing      83
charles       1992       0.0     None     112

In [14]:
df.to_csv('df.csv')
#df.to_excel('df.xls')
#df.to_json('df.json')
#df.to_clipboard()

## Reading Data

In [16]:
people_dict2 = { "weight": pd.Series([69, 84, 113],index=["malice", "mob", "marles"]),
                "birthyear": pd.Series([1985, 1986, 1993], index=["mob", "malice", "marles"],
                name="year"),"children": pd.Series([1, 4], index=["marles", "mob"]),
"hobby": pd.Series(["Sleeping", "Cycling"], index=["malice", "mob"]),}

df2 = pd.DataFrame(people_dict2)
df2

birthyear  children     hobby  weight
malice       1986       NaN  Sleeping      69
marles       1993       1.0       NaN     113
mob          1985       4.0   Cycling      84

In [17]:
df= df.append(df2)

In [18]:
df

birthyear  children     hobby  weight
alice         1985       NaN    Biking      68
bob           1984       3.0   Dancing      83
charles       1992       0.0      None     112
malice        1986       NaN  Sleeping      69
marles        1993       1.0       NaN     113
mob           1985       4.0   Cycling      84

In [20]:
df.head(2)

birthyear  children    hobby  weight
alice       1985       NaN   Biking      68
bob         1984       3.0  Dancing      83

In [21]:
df.tail(4)

birthyear  children     hobby  weight
charles       1992       0.0      None     112
malice        1986       NaN  Sleeping      69
marles        1993       1.0       NaN     113
mob           1985       4.0   Cycling      84

In [22]:
df.shape

(6, 4)

In [23]:
df.describe()

birthyear  children      weight
count     6.000000  4.000000    6.000000
mean   1987.500000  2.000000   88.166667
std       3.937004  1.825742   20.014162
min    1984.000000  0.000000   68.000000
25%    1985.000000  0.750000   72.500000
50%    1985.500000  2.000000   83.500000
75%    1990.500000  3.250000  105.000000
max    1993.000000  4.000000  113.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, alice to mob
Data columns (total 4 columns):
birthyear    6 non-null int64
children     4 non-null float64
hobby        4 non-null object
weight       6 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 240.0+ bytes


## Selection from Data

In [25]:
df['birthyear']

alice      1985
bob        1984
charles    1992
malice     1986
marles     1993
mob        1985
Name: birthyear, dtype: int64

In [26]:
df[['birthyear','hobby']]

birthyear     hobby
alice         1985    Biking
bob           1984   Dancing
charles       1992      None
malice        1986  Sleeping
marles        1993       NaN
mob           1985   Cycling

In [ ]:
df

In [27]:
s.loc['a']

1

In [28]:
s.iloc[0]

1

In [29]:
df.iloc[:,:]

birthyear  children     hobby  weight
alice         1985       NaN    Biking      68
bob           1984       3.0   Dancing      83
charles       1992       0.0      None     112
malice        1986       NaN  Sleeping      69
marles        1993       1.0       NaN     113
mob           1985       4.0   Cycling      84

In [30]:
df.iloc[0,1]

nan

In [31]:
df.loc['alice','children']

nan

In [32]:
df.ix[3]

/Users/eobard/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


birthyear        1986
children          NaN
hobby        Sleeping
weight             69
Name: malice, dtype: object

### Difference between .loc, .iloc and .ix

In [33]:
s = pd.Series(np.nan, index=[49,48,47,46,45, 1, 2, 3, 4, 5])
s

49   NaN
48   NaN
47   NaN
46   NaN
45   NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
dtype: float64

In [37]:
s.iloc[:3]

49   NaN
48   NaN
47   NaN
dtype: float64

## Data Cleaning


In [38]:
df.columns=['a','b','c','d']
#df.columns=['birthyear','children','hobby','weight']

df

a    b         c    d
alice    1985  NaN    Biking   68
bob      1984  3.0   Dancing   83
charles  1992  0.0      None  112
malice   1986  NaN  Sleeping   69
marles   1993  1.0       NaN  113
mob      1985  4.0   Cycling   84

In [39]:
pd.isnull(df)

a      b      c      d
alice    False   True  False  False
bob      False  False  False  False
charles  False  False   True  False
malice   False   True  False  False
marles   False  False   True  False
mob      False  False  False  False

In [40]:
pd.notnull(df)

a      b      c     d
alice    True  False   True  True
bob      True   True   True  True
charles  True   True  False  True
malice   True  False   True  True
marles   True   True  False  True
mob      True   True   True  True

In [42]:
df.dropna(axis=1)

a    d
alice    1985   68
bob      1984   83
charles  1992  112
malice   1986   69
marles   1993  113
mob      1985   84

In [43]:
df.drop('alice')

a    b         c    d
bob      1984  3.0   Dancing   83
charles  1992  0.0      None  112
malice   1986  NaN  Sleeping   69
marles   1993  1.0       NaN  113
mob      1985  4.0   Cycling   84

In [58]:
df.drop('c',axis=1)

a    b    d
alice    1985  NaN   68
bob      1984  3.0   83
charles  1992  0.0  112
malice   1986  NaN   69
marles   1993  1.0  113
mob      1985  4.0   84

In [48]:
df.fillna(6)

a    b         c    d
alice    1985  6.0    Biking   68
bob      1984  3.0   Dancing   83
charles  1992  0.0         6  112
malice   1986  6.0  Sleeping   69
marles   1993  1.0         6  113
mob      1985  4.0   Cycling   84

In [49]:
s.fillna(6)

49    6.0
48    6.0
47    6.0
46    6.0
45    6.0
1     6.0
2     6.0
3     6.0
4     6.0
5     6.0
dtype: float64

In [60]:
df.replace([1992,np.nan],[7,11])

a     b         c    d
alice    1985  11.0    Biking   68
bob      1984   3.0   Dancing   83
charles     7   0.0        11  112
malice   1986  11.0  Sleeping   69
marles   1993   1.0        11  113
mob      1985   4.0   Cycling   84

## Joining/Combining


In [61]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
df_a = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_a

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

In [62]:
raw_data = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
df_b = pd.DataFrame(raw_data, columns = ['subject_id', 'first_name', 'last_name'])
df_b

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [63]:
df_c = df_a.append(df_b)
df_c

subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [ ]:
df_d = pd.concat([df_a,df_b])
df_d

In [65]:
df_inner = pd.merge(df_a,df_b, on ='subject_id', how='inner') 
df_inner

subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

In [66]:
df_outer = pd.merge(df_a, df_b, on ='subject_id', how='outer') 
df_outer

subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan

In [ ]:
df_left = pd.merge(df_a, df_b, on ='subject_id', how='left') 
df_left

In [ ]:
df_right = pd.merge(df_a, df_b, on ='subject_id', how='right') 
df_right

## Filtering data

In [ ]:
df_a

In [69]:
marks = {'Name':['A', 'B', 'C', 'D','E','F','G','I', 'J'],'Marks':[29,34,55,42,31,24,67,99,35],'Class':[1,3,5,2,3,1,4,2,1]}
marks

{'Class': [1, 3, 5, 2, 3, 1, 4, 2, 1],
 'Marks': [29, 34, 55, 42, 31, 24, 67, 99, 35],
 'Name': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'I', 'J']}

In [70]:
mrks = pd.DataFrame(marks)

In [ ]:
mrks

In [72]:
mrks[mrks['Marks'] > 30]

Class  Marks Name
1      3     34    B
2      5     55    C
3      2     42    D
4      3     31    E
6      4     67    G
7      2     99    I
8      1     35    J

In [74]:
mrks.sort_values('Marks')

Class  Marks Name
7      2     99    I
6      4     67    G
2      5     55    C
3      2     42    D
8      1     35    J
1      3     34    B
4      3     31    E
0      1     29    A
5      1     24    F

In [75]:
cls = mrks.groupby(['Class'])

In [78]:
cls

In [81]:
list(cls)

[(1,    Class  Marks Name
  0      1     29    A
  5      1     24    F
  8      1     35    J), (2,    Class  Marks Name
  3      2     42    D
  7      2     99    I), (3,    Class  Marks Name
  1      3     34    B
  4      3     31    E), (4,    Class  Marks Name
  6      4     67    G), (5,    Class  Marks Name
  2      5     55    C)]

In [82]:
cls.describe()

Marks                                                      
      count       mean        std   min    25%   50%    75%   max
Class                                                            
1       3.0  29.333333   5.507571  24.0  26.50  29.0  32.00  35.0
2       2.0  70.500000  40.305087  42.0  56.25  70.5  84.75  99.0
3       2.0  32.500000   2.121320  31.0  31.75  32.5  33.25  34.0
4       1.0  67.000000        NaN  67.0  67.00  67.0  67.00  67.0
5       1.0  55.000000        NaN  55.0  55.00  55.0  55.00  55.0

## Statistical Functions

In [ ]:
mrks.describe()

In [83]:
mrks.mean()

Class     2.444444
Marks    46.222222
dtype: float64

In [84]:
mrks.max()

Class     5
Marks    99
Name      J
dtype: object

In [85]:
mrks.median()

Class     2.0
Marks    35.0
dtype: float64

In [86]:
mrks.std()

Class     1.424001
Marks    24.004051
dtype: float64

In [87]:
mrks.corr()

Class     Marks
Class  1.000000  0.333186
Marks  0.333186  1.000000

# Practice

Import weather_by_cities file and perform all functions